routes.py
# * ----------------------------------------------------------------------------#
# * Imports
# *----------------------------------------------------------------------------#

import datetime
import sys

from flask import (
    Blueprint,
    Flask,
    abort,
    flash,
    redirect,
    render_template,
    request,
    url_for,
)

from utils.caching import cache
from database import db
from forms import ArtistForm, VenueForm, ShowForm
from models.models import Artist, Show, Venue

route_blueprint = Blueprint("routes", __name__)


# *----------------------------------------------------------------------------#
# * Controllers.
# *----------------------------------------------------------------------------#


@route_blueprint.route("/")
@cache.cached(timeout=50)
def index():
    return render_template("pages/home.html")


# * -------------------------------------------------------------------------- #
# *  Venues
# *  ----------------------------------------------------------------


@route_blueprint.route("/venues")
@cache.cached(timeout=50)
def venues():
    venues_list = Venue.query.distinct(Venue.city, Venue.state).all()
    data = [
        {
            "city": venue.city,
            "state": venue.state,
            "venues": [
                {
                    "id": venue.id,
                    "name": venue.name,
                    "num_upcoming_shows": len(
                        [
                            show
                            for show in venue.shows
                            if show.start_time > datetime.datetime.now()
                        ]
                    ),
                }
                for venue in Venue.query.filter_by(city=venue.city).all()
            ],
        }
        for venue in venues_list
    ]

    return render_template("pages/venues.html", areas=data)


@route_blueprint.route("/venues/search", methods=["POST"])
@cache.cached(timeout=50)
def search_venues():
    # Implement search on artists with partial string search
    search_term = request.form.get("search_term", "")
    venues = Venue.query.filter(Venue.name.ilike(f"%{search_term}%")).all()
    data = [
        {
            "id": venue.id,
            "name": venue.name,
            "num_upcoming_shows": len(
                Show.query.filter(Show.venue_id == venue.id)
                .filter(Show.start_time > datetime.now())
                .all()
            ),
        }
        for venue in venues
    ]
    response = {"count": len(venues), "data": data}

    return render_template(
        "pages/search_venues.html",
        results=response,
        search_term=request.form.get("search_term", ""),
    )


@route_blueprint.route("/venues/<int:venue_id>")
@cache.cached(timeout=50)
def show_venue(venue_id):
    # shows the venue page with the given venue_id
    # replace with real venue data from the venues table, using venue_id

    venues = Venue.query.filter(Venue.id == venue_id).first()

    # query for past shows and upcoming shows
    past_shows = (
        Show.query.filter(Show.venue_id == venue_id)
        .filter(Show.start_time < datetime.now())
        .all()
    )
    upcoming_shows = (
        Show.query.filter(Show.venue_id == venue_id)
        .filter(Show.start_time > datetime.now())
        .all()
    )

    # create past shows and upcoming shows list
    past_shows_list = [
        {
            "artist_id": show.artist_id,
            "artist_name": Artist.query.filter(Artist.id == show.artist_id)
            .first()
            .name,
            "artist_image_link": Artist.query.filter(Artist.id == show.artist_id)
            .first()
            .image_link,
            "start_time": str(show.start_time),
        }
        for show in past_shows
    ]

    upcoming_shows_list = [
        {
            "artist_id": show.artist_id,
            "artist_name": Artist.query.filter(Artist.id == show.artist_id)
            .first()
            .name,
            "artist_image_link": Artist.query.filter(Artist.id == show.artist_id)
            .first()
            .image_link,
            "start_time": str(show.start_time),
        }
        for show in upcoming_shows
    ]

    data = {
        "id": venues.id,
        "name": venues.name,
        "genres": venues.genres,
        "address": venues.address,
        "city": venues.city,
        "state": venues.state,
        "phone": venues.phone,
        "website_link": venues.website_link,
        "facebook_link": venues.facebook_link,
        "seeking_talent": venues.seeking_talent,
        "seeking_description": venues.seeking_description,
        "image_link": venues.image_link,
        "past_shows": past_shows_list,
        "upcoming_shows": upcoming_shows_list,
        "past_shows_count": len(past_shows_list),
        "upcoming_shows_count": len(upcoming_shows_list),
    }

    return render_template("pages/show_venue.html", venue=data)


# *  ----------------------------------------------------------------
# *  Create Venue
# *  ----------------------------------------------------------------


@route_blueprint.route("/venues/create", methods=["GET"])
@cache.cached(timeout=50)
def create_venue_form():
    # Renders the form to create a new venue
    form = VenueForm()

    return render_template("forms/new_venue.html", form=form)


@route_blueprint.route("/venues/create", methods=["POST"])
@cache.cached(timeout=50)
def create_venue_submission():
    # Insert form data as a new Venue record in the db, instead
    # Modify data to be the data object returned from db insertion
    error = False
    form = VenueForm(request.form)
    if form.validate():
        try:
            venue = Venue(
                name=form.name.data,
                city=form.city.data,
                state=form.state.data,
                address=form.address.data,
                phone=form.phone.data,
                genres=form.genres.data,
                facebook_link=form.facebook_link.data,
                image_link=form.image_link.data,
                website_link=form.website_link.data,
                seeking_talent=form.seeking_talent.data,
                seeking_description=form.seeking_description.data,
            )
            db.session.add(venue)
            db.session.commit()
        except Exception as e:
            error = True
            db.session.rollback()
            print(f"Error: {e}")
        finally:
            db.session.close()
    else:
        flash(
            "An error occurred. Venue " + request.form["name"] + " could not be listed."
        )
        return render_template("forms/new_venue.html", form=form)

    # on successful db insert, flash success
    if error:
        flash(
            "An error occurred. Venue " + request.form["name"] + " could not be listed."
        )
    # see: http://flask.pocoo.org/docs/1.0/patterns/flashing/
    if not error:
        flash("Venue " + request.form["name"] + " was successfully listed!")
    return render_template("pages/home.html")


@route_blueprint.route("/venues/<venue_id>", methods=["DELETE"])
def delete_venue(venue_id):
    # Delete venue record from db
    error = False
    try:
        venue = Venue.query.get(venue_id)
        db.session.delete(venue)
        db.session.commit()
    except Exception:
        error = True
        db.session.rollback()
    finally:
        db.session.close()
    if error:
        flash(
            "An error occurred. Venue "
            + request.form["name"]
            + " could not be deleted."
        )
    else:
        flash("Venue " + request.form["name"] + " was successfully deleted!")

    return render_template("pages/home.html")


# *  ----------------------------------------------------------------
# *  ARTISTS
# *  ----------------------------------------------------------------


@route_blueprint.route("/artists")
@cache.cached(timeout=50)
def artists():
    # Get the artists from the database
    artists = Artist.query.all()
    data = [{"id": artist.id, "name": artist.name} for artist in artists]
    return render_template("pages/artists.html", artists=data)


@route_blueprint.route("/artists/search", methods=["POST"])
@cache.cached(timeout=50)
def search_artists():
    # Search on artist records with partial string search.
    search_term = request.form.get("search_term", "")
    artists = Artist.query.filter(Artist.name.ilike(f"%{search_term}%")).all()
    data = [
        {
            "id": artist.id,
            "name": artist.name,
            "num_upcoming_shows": len(
                Show.query.filter(Show.artist_id == artist.id)
                .filter(Show.start_time > datetime.now())
                .all()
            ),
        }
        for artist in artists
    ]
    response = {"count": len(artists), "data": data}

    return render_template(
        "pages/search_artists.html",
        results=response,
        search_term=request.form.get("search_term", ""),
    )


@route_blueprint.route("/artists/<int:artist_id>")
@cache.cached(timeout=50)
def show_artist(artist_id):
    # shows the artist page with the given artist_id
    artist = Artist.query.get(artist_id)
    past_shows = (
        Show.query.filter(Show.artist_id == artist_id)
        .filter(Show.start_time < datetime.now())
        .all()
    )
    upcoming_shows = (
        Show.query.filter(Show.artist_id == artist_id)
        .filter(Show.start_time > datetime.now())
        .all()
    )

    # filter venues by past shows
    past_shows_list = [
        {
            "venue_id": show.venue_id,
            "venue_name": Venue.query.filter(Venue.id == show.venue_id).first().name,
            "venue_image_link": Venue.query.filter(Venue.id == show.venue_id)
            .first()
            .image_link,
            "start_time": str(show.start_time),
        }
        for show in past_shows
    ]

    # filter venues by upcoming shows
    upcoming_shows_list = [
        {
            "venue_id": show.venue_id,

templates/layouts/form.html
<!doctype html>
<head>
<meta charset="utf-8">
<title>{% block title %}{% endblock %}</title>

<!-- meta -->
<meta name="description" content="">
<meta name="author" content="">
<meta name="viewport" content="width=device-width,initial-scale=1">
<!-- /meta -->

<!-- styles -->
<link type="text/css" rel="stylesheet" href="/static/css/font-awesome-4.1.0.min.css" />
<link type="text/css" rel="stylesheet" href="/static/css/bootstrap-3.1.1.min.css">
<link type="text/css" rel="stylesheet" href="/static/css/bootstrap-theme-3.1.1.min.css" />
<link type="text/css" rel="stylesheet" href="/static/css/layout.main.css" />
<link type="text/css" rel="stylesheet" href="/static/css/main.css" />
<link type="text/css" rel="stylesheet" href="/static/css/main.responsive.css" />
<link type="text/css" rel="stylesheet" href="/static/css/main.quickfix.css" />
<!-- /styles -->

<!-- favicons -->
<link rel="shortcut icon" href="/static/ico/favicon.png">
<link rel="apple-touch-icon-precomposed" sizes="144x144" href="/static/ico/apple-touch-icon-144-precomposed.png">
<link rel="apple-touch-icon-precomposed" sizes="114x114" href="/static/ico/apple-touch-icon-114-precomposed.png">
<link rel="apple-touch-icon-precomposed" sizes="72x72" href="/static/ico/apple-touch-icon-72-precomposed.png">
<link rel="apple-touch-icon-precomposed" href="/static/ico/apple-touch-icon-57-precomposed.png">
<link rel="shortcut icon" href="/static/ico/favicon.png">
<!-- /favicons -->

<!-- scripts -->
<script src="/static/js/libs/modernizr-2.8.2.min.js"></script>
<!--[if lt IE 9]><script src="/static/js/libs/respond-1.4.2.min.js"></script><![endif]-->
<!-- /scripts -->

</head>
<body class="form-only-page">

  <div class="container">

    {% with messages = get_flashed_messages() %}
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-warning fade in">
            <a class="close" data-dismiss="alert">&times;</a>
            {{ message }}
          </div>
        {% endfor %}
      {% endif %}
    {% endwith %}

    {% block content %}{% endblock %}

  </div>

  <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <script>window.jQuery || document.write('<script type="text/javascript" src="/static/js/libs/jquery-1.11.1.min.js"><\/script>')</script>
  <script type="text/javascript" src="/static/js/libs/bootstrap-3.1.1.min.js" defer></script>
  <script type="text/javascript" src="/static/js/plugins.js" defer></script>
  <script type="text/javascript" src="/static/js/script.js" defer></script>

</body>
</html>

templates/layouts/main.html
<!doctype html>
<head>
<meta charset="utf-8">
<title>{% block title %}{% endblock %}</title>

<!-- meta -->
<meta name="description" content="">
<meta name="author" content="">
<meta name="viewport" content="width=device-width,initial-scale=1">
<!-- /meta -->

<!-- styles -->
<link type="text/css" rel="stylesheet" href="/static/css/bootstrap.min.css">
<link type="text/css" rel="stylesheet" href="/static/css/layout.main.css" />
<link type="text/css" rel="stylesheet" href="/static/css/main.css" />
<link type="text/css" rel="stylesheet" href="/static/css/main.responsive.css" />
<link type="text/css" rel="stylesheet" href="/static/css/main.quickfix.css" />
<!-- /styles -->

<!-- favicons -->
<link rel="shortcut icon" href="/static/icon/favicon.png">
<link rel="apple-touch-icon-precomposed" sizes="144x144" href="/static/ico/apple-touch-icon-144-precomposed.png">
<link rel="apple-touch-icon-precomposed" sizes="114x114" href="/static/ico/apple-touch-icon-114-precomposed.png">
<link rel="apple-touch-icon-precomposed" sizes="72x72" href="/static/ico/apple-touch-icon-72-precomposed.png">
<link rel="apple-touch-icon-precomposed" href="/static/ico/apple-touch-icon-57-precomposed.png">
<link rel="shortcut icon" href="/static/ico/favicon.png">
<!-- /favicons -->

<!-- scripts -->
<script src="https://kit.fontawesome.com/af77674fe5.js"></script>
<script src="/static/js/libs/modernizr-2.8.2.min.js"></script>
<script src="/static/js/libs/moment.min.js"></script>
<script type="text/javascript" src="/static/js/script.js" defer></script>
<!--[if lt IE 9]><script src="/static/js/libs/respond-1.4.2.min.js"></script><![endif]-->
<!-- /scripts -->
</head>
<body>

<!-- Wrap all page content here -->
<div id="wrap">

    <!-- Fixed navbar -->
    <div class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">🔥</a>
        </div>
        <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
            <li>
            {% if (request.endpoint == 'venues') or
                (request.endpoint == 'search_venues') or
                (request.endpoint == 'show_venue') %}
            <form class="search" method="post" action="/venues/search">
                <input class="form-control"
                type="search"
                name="search_term"
                placeholder="Find a venue"
                aria-label="Search">
            </form>
            {% endif %}
            {% if (request.endpoint == 'artists') or
                (request.endpoint == 'search_artists') or
                (request.endpoint == 'show_artist') %}
            <form class="search" method="post" action="/artists/search">
                <input class="form-control"
                type="search"
                name="search_term"
                placeholder="Find an artist"
                aria-label="Search">
            </form>
            {% endif %}
            </li>
        </ul>
        <ul class="nav navbar-nav">
            <li {% if request.endpoint == 'venues' %} class="active" {% endif %}><a href="{{ url_for('routes.venues') }}">Venues</a></li>
            <li {% if request.endpoint == 'artists' %} class="active" {% endif %}><a href="{{ url_for('routes.artists') }}">Artists</a></li>
            <li {% if request.endpoint == 'shows' %} class="active" {% endif %}><a href="{{ url_for('routes.shows') }}">Shows</a></li>
        </ul>
        </div><!--/.nav-collapse -->
    </div>
    </div>

    <!-- Begin page content -->
    <main id="content" role="main" class="container">

    {% with messages = get_flashed_messages() %}
        {% if messages %}
        {% for message in messages %}
            <div class="alert alert-block alert-info fade in">
            <a class="close" data-dismiss="alert">&times;</a>
            {{ message }}
            </div>
        {% endfor %}
        {% endif %}
    {% endwith %}

    {% block content %}{% endblock %}
    
    </main>

</div>

<div id="footer">
    <div class="container">
    <p>Fyyur &copy; All Rights Reserved.</p>
    {% block footer %}
    {% endblock %}
    <p>Backend built by 
        <a class="author" target="_blank" href="https://github.com/mavhungutrezzy">Mavhungu Adivhaho</a>
    </p>
    </div>
</div>

<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script>window.jQuery || document.write('<script type="text/javascript" src="/static/js/libs/jquery-1.11.1.min.js"><\/script>')</script>
<script type="text/javascript" src="/static/js/libs/bootstrap-3.1.1.min.js" defer></script>
<script type="text/javascript" src="/static/js/plugins.js" defer></script>

</body>
</html>