routes.py
# * ----------------------------------------------------------------------------#
# * Imports
# *----------------------------------------------------------------------------#

import datetime
import sys

from flask import (
    Blueprint,
    Flask,
    abort,
    flash,
    redirect,
    render_template,
    request,
    url_for,
)

from utils.caching import cache
from database import db
from forms import ArtistForm, VenueForm, ShowForm
from models.models import Artist, Show, Venue

route_blueprint = Blueprint("routes", __name__)


# *----------------------------------------------------------------------------#
# * Controllers.
# *----------------------------------------------------------------------------#


@route_blueprint.route("/")
@cache.cached(timeout=50)
def index():
    return render_template("pages/home.html")


# * -------------------------------------------------------------------------- #
# *  Venues
# *  ----------------------------------------------------------------


@route_blueprint.route("/venues")
@cache.cached(timeout=50)
def venues():
    venues_list = Venue.query.distinct(Venue.city, Venue.state).all()
    data = [
        {
            "city": venue.city,
            "state": venue.state,
            "venues": [
                {
                    "id": venue.id,
                    "name": venue.name,
                    "num_upcoming_shows": len(
                        [
                            show
                            for show in venue.shows
                            if show.start_time > datetime.datetime.now()
                        ]
                    ),
                }
                for venue in Venue.query.filter_by(city=venue.city).all()
            ],
        }
        for venue in venues_list
    ]

    return render_template("pages/venues.html", areas=data)


@route_blueprint.route("/venues/search", methods=["POST"])
@cache.cached(timeout=50)
def search_venues():
    # Implement search on artists with partial string search
    search_term = request.form.get("search_term", "")
    venues = Venue.query.filter(Venue.name.ilike(f"%{search_term}%")).all()
    data = [
        {
            "id": venue.id,
            "name": venue.name,
            "num_upcoming_shows": len(
                Show.query.filter(Show.venue_id == venue.id)
                .filter(Show.start_time > datetime.now())
                .all()
            ),
        }
        for venue in venues
    ]
    response = {"count": len(venues), "data": data}

    return render_template(
        "pages/search_venues.html",
        results=response,
        search_term=request.form.get("search_term", ""),
    )


@route_blueprint.route("/venues/<int:venue_id>")
@cache.cached(timeout=50)
def show_venue(venue_id):
    # shows the venue page with the given venue_id
    # replace with real venue data from the venues table, using venue_id

    venues = Venue.query.filter(Venue.id == venue_id).first()

    # query for past shows and upcoming shows
    past_shows = (
        Show.query.filter(Show.venue_id == venue_id)
        .filter(Show.start_time < datetime.now())
        .all()
    )
    upcoming_shows = (
        Show.query.filter(Show.venue_id == venue_id)
        .filter(Show.start_time > datetime.now())
        .all()
    )

    # create past shows and upcoming shows list
    past_shows_list = [
        {
            "artist_id": show.artist_id,
            "artist_name": Artist.query.filter(Artist.id == show.artist_id)
            .first()
            .name,
            "artist_image_link": Artist.query.filter(Artist.id == show.artist_id)
            .first()
            .image_link,
            "start_time": str(show.start_time),
        }
        for show in past_shows
    ]

    upcoming_shows_list = [
        {
            "artist_id": show.artist_id,
            "artist_name": Artist.query.filter(Artist.id == show.artist_id)
            .first()
            .name,
            "artist_image_link": Artist.query.filter(Artist.id == show.artist_id)
            .first()
            .image_link,
            "start_time": str(show.start_time),
        }
        for show in upcoming_shows
    ]

    data = {
        "id": venues.id,
        "name": venues.name,
        "genres": venues.genres,
        "address": venues.address,
        "city": venues.city,
        "state": venues.state,
        "phone": venues.phone,
        "website_link": venues.website_link,
        "facebook_link": venues.facebook_link,
        "seeking_talent": venues.seeking_talent,
        "seeking_description": venues.seeking_description,
        "image_link": venues.image_link,
        "past_shows": past_shows_list,
        "upcoming_shows": upcoming_shows_list,
        "past_shows_count": len(past_shows_list),
        "upcoming_shows_count": len(upcoming_shows_list),
    }

    return render_template("pages/show_venue.html", venue=data)


# *  ----------------------------------------------------------------
# *  Create Venue
# *  ----------------------------------------------------------------


@route_blueprint.route("/venues/create", methods=["GET"])
@cache.cached(timeout=50)
def create_venue_form():
    # Renders the form to create a new venue
    form = VenueForm()

    return render_template("forms/new_venue.html", form=form)


@route_blueprint.route("/venues/create", methods=["POST"])
@cache.cached(timeout=50)
def create_venue_submission():
    # Insert form data as a new Venue record in the db, instead
    # Modify data to be the data object returned from db insertion
    error = False
    form = VenueForm(request.form)
    if form.validate():
        try:
            venue = Venue(
                name=form.name.data,
                city=form.city.data,
                state=form.state.data,
                address=form.address.data,
                phone=form.phone.data,
                genres=form.genres.data,
                facebook_link=form.facebook_link.data,
                image_link=form.image_link.data,
                website_link=form.website_link.data,
                seeking_talent=form.seeking_talent.data,
                seeking_description=form.seeking_description.data,
            )
            db.session.add(venue)
            db.session.commit()
        except Exception as e:
            error = True
            db.session.rollback()
            print(f"Error: {e}")
        finally:
            db.session.close()
    else:
        flash(
            "An error occurred. Venue " + request.form["name"] + " could not be listed."
        )
        return render_template("forms/new_venue.html", form=form)

    # on successful db insert, flash success
    if error:
        flash(
            "An error occurred. Venue " + request.form["name"] + " could not be listed."
        )
    # see: http://flask.pocoo.org/docs/1.0/patterns/flashing/
    if not error:
        flash("Venue " + request.form["name"] + " was successfully listed!")
    return render_template("pages/home.html")


@route_blueprint.route("/venues/<venue_id>", methods=["DELETE"])
def delete_venue(venue_id):
    # Delete venue record from db
    error = False
    try:
        venue = Venue.query.get(venue_id)
        db.session.delete(venue)
        db.session.commit()
    except Exception:
        error = True
        db.session.rollback()
    finally:
        db.session.close()
    if error:
        flash(
            "An error occurred. Venue "
            + request.form["name"]
            + " could not be deleted."
        )
    else:
        flash("Venue " + request.form["name"] + " was successfully deleted!")

    return render_template("pages/home.html")


# *  ----------------------------------------------------------------
# *  ARTISTS
# *  ----------------------------------------------------------------


@route_blueprint.route("/artists")
@cache.cached(timeout=50)
def artists():
    # Get the artists from the database
    artists = Artist.query.all()
    data = [{"id": artist.id, "name": artist.name} for artist in artists]
    return render_template("pages/artists.html", artists=data)


@route_blueprint.route("/artists/search", methods=["POST"])
@cache.cached(timeout=50)
def search_artists():
    # Search on artist records with partial string search.
    search_term = request.form.get("search_term", "")
    artists = Artist.query.filter(Artist.name.ilike(f"%{search_term}%")).all()
    data = [
        {
            "id": artist.id,
            "name": artist.name,
            "num_upcoming_shows": len(
                Show.query.filter(Show.artist_id == artist.id)
                .filter(Show.start_time > datetime.now())
                .all()
            ),
        }
        for artist in artists
    ]
    response = {"count": len(artists), "data": data}

    return render_template(
        "pages/search_artists.html",
        results=response,
        search_term=request.form.get("search_term", ""),
    )


@route_blueprint.route("/artists/<int:artist_id>")
@cache.cached(timeout=50)
def show_artist(artist_id):
    # shows the artist page with the given artist_id
    artist = Artist.query.get(artist_id)
    past_shows = (
        Show.query.filter(Show.artist_id == artist_id)
        .filter(Show.start_time < datetime.now())
        .all()
    )
    upcoming_shows = (
        Show.query.filter(Show.artist_id == artist_id)
        .filter(Show.start_time > datetime.now())
        .all()
    )

    # filter venues by past shows
    past_shows_list = [
        {
            "venue_id": show.venue_id,
            "venue_name": Venue.query.filter(Venue.id == show.venue_id).first().name,
            "venue_image_link": Venue.query.filter(Venue.id == show.venue_id)
            .first()
            .image_link,
            "start_time": str(show.start_time),
        }
        for show in past_shows
    ]

    # filter venues by upcoming shows
    upcoming_shows_list = [
        {
            "venue_id": show.venue_id,

templates/forms/edit_artist.html
{% extends 'layouts/main.html' %}
{% block title %}Edit Artist{% endblock %}
{% block content %}
  <div class="form-wrapper">
    <form class="form" method="post" action="/artists/{{artist.id}}/edit">
      <h3 class="form-heading">Edit artist <em>{{ artist.name }}</em></h3>
      <div class="form-group">
        <label for="name">Name</label>
        {{ form.name(class_ = 'form-control', autofocus = true) }}
      </div>
      <div class="form-group">
          <label>City & State</label>
          <div class="form-inline">
            <div class="form-group">
              {{ form.city(class_ = 'form-control', placeholder='City', autofocus = true) }}
            </div>
            <div class="form-group">
              {{ form.state(class_ = 'form-control', placeholder='State', autofocus = true) }}
            </div>
          </div>
      </div>
      <div class="form-group">
          <label for="phone">Phone</label>
          {{ form.phone(class_ = 'form-control', placeholder='xxx-xxx-xxxx', autofocus = true) }}
        </div>
      <div class="form-group">
        <label for="genres">Genres</label>
        <small>Ctrl+Click to select multiple</small>
        {{ form.genres(class_ = 'form-control', placeholder='Genres, separated by commas', autofocus = true) }}
      </div>
      <div class="form-group">
          <label for="facebook_link">Facebook Link</label>
          {{ form.facebook_link(class_ = 'form-control', placeholder='http://', autofocus = true) }}
        </div>
      
      <div class="form-group">
          <label for="image_link">Image Link</label>
          {{ form.image_link(class_ = 'form-control', placeholder='http://', autofocus = true) }}
      </div>

      <div class="form-group">
            <label for="website_link">Website Link</label>
            {{ form.website_link(class_ = 'form-control', placeholder='http://', autofocus = true) }}
      </div>

      <div class="form-group">
          <label for="seeking_venue">Looking for Venues</label>
          {{ form.seeking_venue(placeholder='Venue', autofocus = true) }}
      </div>

      <div class="form-group">
          <label for="seeking_description">Seeking Description</label>
          {{ form.seeking_description(class_ = 'form-control', autofocus = true) }}
      </div>
      
      <input type="submit" value="Edit Artist" class="btn btn-primary btn-lg btn-block">
    </form>
  </div>
{% endblock %}

templates/forms/edit_venue.html
{% extends 'layouts/main.html' %}
{% block title %}Edit Venue{% endblock %}
{% block content %}
  <div class="form-wrapper">
    <form class="form" method="post" action="/venues/{{venue.id}}/edit">
      <h3 class="form-heading">Edit venue <em>{{ venue.name }}</em> <a href="{{ url_for('routes.index') }}" title="Back to homepage"><i class="fa fa-home pull-right"></i></a></h3>
      <div class="form-group">
        <label for="name">Name</label>
        {{ form.name(class_ = 'form-control', autofocus = true) }}
      </div>
      <div class="form-group">
          <label>City & State</label>
          <div class="form-inline">
            <div class="form-group">
              {{ form.city(class_ = 'form-control', placeholder='City', autofocus = true) }}
            </div>
            <div class="form-group">
              {{ form.state(class_ = 'form-control', placeholder='State', autofocus = true) }}
            </div>
          </div>
      </div>
      <div class="form-group">
        <label for="address">Address</label>
        {{ form.address(class_ = 'form-control', autofocus = true) }}
      </div>
      <div class="form-group">
          <label for="phone">Phone</label>
          {{ form.phone(class_ = 'form-control', placeholder='xxx-xxx-xxxx', autofocus = true) }}
        </div>
      <div class="form-group">
        <label for="genres">Genres</label>
        <small>Ctrl+Click to select multiple</small>
        {{ form.genres(class_ = 'form-control', placeholder='Genres, separated by commas', autofocus = true) }}
      </div>
      <div class="form-group">
          <label for="facebook_link">Facebook Link</label>
          {{ form.facebook_link(class_ = 'form-control', placeholder='http://', autofocus = true) }}
       </div>
      
       <div class="form-group">
          <label for="image_link">Image Link</label>
          {{ form.image_link(class_ = 'form-control', placeholder='http://', autofocus = true) }}
       </div>

       <div class="form-group">
              <label for="website_link">Website Link</label>
              {{ form.website_link(class_ = 'form-control', placeholder='http://', autofocus = true) }}
        </div>

        <div class="form-group">
             <label for="seeking_talent">Looking for Talent</label>
             {{ form.seeking_talent(placeholder='Venue', autofocus = true) }}
        </div>

        <div class="form-group">
            <label for="seeking_description">Seeking Description</label>
            {{ form.seeking_description(class_ = 'form-control', autofocus = true) }}
          </div>
      
      <input type="submit" value="Edit Venue" class="btn btn-primary btn-lg btn-block">
    </form>
  </div>
{% endblock %}

templates/forms/new_artist.html
{% extends 'layouts/main.html' %}
{% block title %}New Artist{% endblock %}
{% block content %}
  <div class="form-wrapper">
    <form method="post" class="form">
      <h3 class="form-heading">List a new artist</h3>
      <div class="form-group">
        <label for="name">Name</label>
        {{ form.name(class_ = 'form-control', autofocus = true) }}
      </div>
      <div class="form-group">
          <label>City & State</label>
          <div class="form-inline">
            <div class="form-group">
              {{ form.city(class_ = 'form-control', placeholder='City', autofocus = true) }}
            </div>
            <div class="form-group">
              {{ form.state(class_ = 'form-control', placeholder='State', autofocus = true) }}
            </div>
          </div>
      </div>
      <div class="form-group">
          <label for="phone">Phone</label>
          {{ form.phone(class_ = 'form-control', placeholder='xxx-xxx-xxxx', autofocus = true) }}
        </div>
      <div class="form-group">
        <label for="genres">Genres</label>
        <small>Ctrl+Click to select multiple</small>
        {{ form.genres(class_ = 'form-control', placeholder='Genres, separated by commas', autofocus = true) }}
      </div>
      <div class="form-group">
          <label for="facebook_link">Facebook Link</label>
          {{ form.facebook_link(class_ = 'form-control', placeholder='http://', autofocus = true) }}
        </div>
      
        <div class="form-group">
          <label for="image_link">Image Link</label>
          {{ form.image_link(class_ = 'form-control', placeholder='http://', autofocus = true) }}
        </div>

        <div class="form-group">
            <label for="website_link">Website Link</label>
            {{ form.website_link(class_ = 'form-control', placeholder='http://', autofocus = true) }}
          </div>

          <div class="form-group">
              <label for="seeking_venue">Looking for Venues</label>
              {{ form.seeking_venue(placeholder='Venue', autofocus = true) }}
          </div>

          <div class="form-group">
              <label for="seeking_description">Seeking Description</label>
              {{ form.seeking_description(class_ = 'form-control', autofocus = true) }}
            </div>
      <input type="submit" value="Create Artist" class="btn btn-primary btn-lg btn-block">
    </form>
  </div>
{% endblock %}

templates/forms/new_show.html
{% extends 'layouts/main.html' %}
{% block title %}New Show Listing{% endblock %}
{% block content %}
  <div class="form-wrapper">
    <form method="post" class="form">
      <h3 class="form-heading">List a new show</h3>
      <div class="form-group">
        <label for="artist_id">Artist ID</label>
        <small>ID can be found on the Artist's Page</small>
        {{ form.artist_id(class_ = 'form-control', autofocus = true) }}
      </div>
      <div class="form-group">
        <label for="venue_id">Venue ID</label>
        <small>ID can be found on the Venue's Page</small>
        {{ form.venue_id(class_ = 'form-control', autofocus = true) }}
      </div>
      <div class="form-group">
          <label for="start_time">Start Time</label>
          {{ form.start_time(class_ = 'form-control', placeholder='YYYY-MM-DD HH:MM', autofocus = true) }}
        </div>
      <input type="submit" value="Create Venue" class="btn btn-primary btn-lg btn-block">
    </form>
  </div>
{% endblock %}

templates/forms/new_venue.html
{% extends 'layouts/main.html' %}
{% block title %}New Venue{% endblock %}
{% block content %}
  <div class="form-wrapper">
    <form method="post" class="form" action="/venues/create">
      <h3 class="form-heading">List a new venue <a href="{{ url_for('routes.index') }}" title="Back to homepage"><i class="fa fa-home pull-right"></i></a></h3>
      <div class="form-group">
        <label for="name">Name</label>
        {{ form.name(class_ = 'form-control', autofocus = true) }}
      </div>
      <div class="form-group">
          <label>City & State</label>
          <div class="form-inline">
            <div class="form-group">
              {{ form.city(class_ = 'form-control', placeholder='City', autofocus = true) }}
            </div>
            <div class="form-group">
              {{ form.state(class_ = 'form-control', placeholder='State', autofocus = true) }}
            </div>
          </div>
      </div>
      <div class="form-group">
        <label for="address">Address</label>
        {{ form.address(class_ = 'form-control', autofocus = true) }}
      </div>
      <div class="form-group">
          <label for="phone">Phone</label>
          {{ form.phone(class_ = 'form-control', placeholder='xxx-xxx-xxxx', autofocus = true) }}
        </div>
      <div class="form-group">
        <label for="genres">Genres</label>
        <small>Ctrl+Click to select multiple</small>
        {{ form.genres(class_ = 'form-control', placeholder='Genres, separated by commas', autofocus = true) }}
      </div>
      
      <div class="form-group">
          <label for="facebook_link">Facebook Link</label>
          {{ form.facebook_link(class_ = 'form-control', placeholder='http://', autofocus = true) }}
       </div>
      
       <div class="form-group">
          <label for="image_link">Image Link</label>
          {{ form.image_link(class_ = 'form-control', placeholder='http://', autofocus = true) }}
       </div>

       <div class="form-group">
            <label for="website_link">Website Link</label>
            {{ form.website_link(class_ = 'form-control', placeholder='http://', autofocus = true) }}
       </div>

       <div class="form-group">
             <label for="seeking_talent">Looking for Talent</label>
             {{ form.seeking_talent(placeholder='Venue', autofocus = true) }}
       </div>

       <div class="form-group">
            <label for="seeking_description">Seeking Description</label>
            {{ form.seeking_description(class_ = 'form-control', placeholder='Description', autofocus = true) }}
       </div>
      <input type="submit" value="Create Venue" class="btn btn-primary btn-lg btn-block">
    </form>
  </div>
{% endblock %}